### ISSUE TITLE
AMI is not ENA-enabled error

### ISSUE THREAD

**Issue by DonSchenck** [redhat-developer-demos/openshift-hybridizer#10]
I'm using AMI ami-8b44f2f3 in region us-west-2.

```
TASK [cloud-resources : AWS Create All in one OpenShift Node] ******************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Instance creation failed => InvalidParameterCombination: Enhanced networking with the Elastic Network Adapter (ENA) is required for the 'm5.xlarge' instance type. Ensure that you are using an AMI that is enabled for ENA."}

```

**Comment by rafabene** [comment]
I'm facing the same error for us-east-1:

> TASK [cloud-resources : AWS Create All in one OpenShift Node] ******************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Instance creation failed => InvalidParameterCombination: Enhanced networking with the Elastic Network Adapter (ENA) is required for the 'm5.xlarge' instance type. Ensure that you are using an AMI that is enabled for ENA."}

**Comment by rafabene** [comment]
It seems that is was caused by using a CentOS 6 AMI. Can you confirm that @DonSchenck and try with a CentOS7?
