### ISSUE TITLE
Install Origin webconsole

### ISSUE THREAD

**Issue by rafabene** [redhat-developer-demos/openshift-hybridizer#16]
After the script ./deploy.sh The URL at https://IP:8443 shows

> missing service (service "webconsole" not found)
missing route (service "webconsole" not found)

It seems that the webconsole should be installed according to https://github.com/openshift/origin/issues/18207

**Comment by kameshsampath** [comment]
can you please check with latest master and validate ? some amis had issues the one which works for us-west-1 is `ami-4826c22b`. Please validate

**Comment by rafabene** [comment]
That worked for me. Thanks. Now we need to fill the valid region/AMIs at https://github.com/redhat-developer-demos/openshift-hybridizer/blob/master/docs/_includes/aws-amis.adoc
