### ISSUE TITLE
Failed to deprovision AWS

### ISSUE THREAD

**Issue by rafabene** [redhat-developer-demos/openshift-hybridizer#17]
It fails with the following message

> TASK [cloud-resources-rollback : AWS Delete All in one OpenShift Node] *********
fatal: [localhost]: FAILED! => {"changed": false, "msg": "instance_ids list is required for absent state"}
localhost                  : ok=2    changed=0    unreachable=0    failed=1

**Comment by kameshsampath** [comment]
@rafabene  commit 283419ef6b37d2c7800a397ced84cab1ca931765 solves the issues, please validate

**Comment by rafabene** [comment]
Validated.
