### ISSUE TITLE
AWS error: Enhanced networking with ENA is required for m5.xlarge instance

### ISSUE THREAD

**Issue by DonSchenck** [redhat-developer-demos/openshift-hybridizer#20]
Getting the following error while attempting to provision the Amazon VM:

`TASK [cloud-resources : AWS Create All in one OpenShift Node] ******************

fatal: [localhost]: FAILED! => {"changed": false, "msg": "Instance creation failed => InvalidParameterCombination: Enhanced networking with the Elastic Network Adapter (ENA) is required for the 'm5.xlarge' instance type. Ensure that you are using an AMI that is enabled for ENA."}
localhost                  

: ok=9    changed=0    unreachable=0    failed=1   `

**Comment by DonSchenck** [comment]
I solved this by using image   image: "ami-00f7c900d2e7133e1"

**Comment by rafabene** [comment]
What region? This ami number seems too large.

**Comment by rafabene** [comment]
We should use the provided combinations to avoid errors: https://github.com/redhat-developer-demos/openshift-hybridizer/blob/master/docs/_includes/aws-amis.adoc
