### ISSUE TITLE
Adding users does not work as described

### ISSUE THREAD

**Issue by elmiko** [redhat-developer-demos/openshift-hybridizer#31]
# what i did

* created a custer as described in the README
* changed dir to `out/gcp`
* modified the `openshift_users.yaml` file to add a custom named user
* ran `add-openshift-users.sh`

# expected results

my custom user `fred` and the `admin` user would be added to `/etc/origin/master/htpasswd` on the host and i could login.

# actual results

`/etc/origin/master/htpasswd` is empty on the server and i am unable to login.

# openshift_users.yaml

the file i used

```
---

# Add or modify the users in this list and rerun the add-openshift-users.sh 
# to have the users add/updated in OpenShift htpasswd file
openshift_users:
    - {username: "fred",password: "supers3cret"}
    - {username: "admin",password: "supers3cretAdmin"}
# Add the List of users to be deleted from OpenShift 
openshift_delete_users:
#    - developer
```

**Comment by kameshsampath** [comment]
@elmiko - there was some package issue i fixed it now, Can you please try now and let me know ? it will be great if you attach some logs for me to analyse and fix

**Comment by elmiko** [comment]
@kameshsampath yes, it does work now. thank you!

i will close this issue.
